<a href="https://colab.research.google.com/github/dae9999nam/SL_Blog/blob/main/DeepLearningStudy_Jul24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch Self Learning Study**
###Reference: https://pytorch.org/docs/stable/
###Youtube source: https://www.youtube.com/watch?v=V_xro1bcAuA&t=2598s

Start Date: 2024.07.24

Notebook Setting: T4 GPU

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


torch version: 2.3.1 cubaversion: 1.2.1

##1. Introduction to Tensors


###1-1.Creating Tensors and observe the characters

In [2]:
#Scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#vectors
vectors = torch.tensor([1,1])
vectors

tensor([1, 1])

In [6]:
vectors.ndim

1

In [7]:
vectors.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSORS
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

#####Variable name for scalar and vector are represented by lower case
#####Variable name for MATRIX and TENSOR are represented by upper case

###1.2 Creating Random Tensors
####Why random tensor
#####Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [14]:
#Create random tensors
random_tensor = torch.rand(3,4) # == torch.rand(size=(3,4))
random_tensor

tensor([[0.9336, 0.4521, 0.6500, 0.9257],
        [0.6043, 0.0626, 0.4825, 0.8052],
        [0.7144, 0.4887, 0.6587, 0.2789]])

In [15]:
#Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) #height, width, colour channel (R,G,B)
# can be torch.rand(size=(3, 224, 224)) => parameters in colour channel, height, width order
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###1.3 Creating Tensors with all zeros and ones

In [16]:
##Tensors with zeros and ones
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
##reasons for floating points in the tensors
#default setting for dtype of tensor is float32
ones.dtype

torch.float32

###Usage of Zero tensors
######Zero tensor can be used to make the target tensor or specific column or row to be zero by multiplying corresponding zero tensor

```
zeros * random_tensor
```



###1.4 Creating a range of tensors and tensors-like


In [19]:
#Use torch.arange(start, end, step)
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
#Creating tensors-like : create same size of tensor as input tensor
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###1.5 Tensor Datatype
####**Note:** Tensor datatype is one of the three big errors you will run into with Pytorch and Deep Learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [21]:
#Float32 Tensor
Float_32_tensor = torch.tensor([3., 6., 9.], dtype=None) #The default datatype of tensor is float32
Float_32_tensor.dtype

torch.float32

In [22]:
Test_tensor = torch.tensor([3., 6., 9.], dtype=torch.float16)
Test_tensor.dtype


torch.float16

In [23]:
Test_tensor = torch.tensor([3.,6.,9.],
                           dtype=torch.float32,#what datatype tensor is
                           device=None,  #what device your tensor is on
                           requires_grad=False) #whether to track gradients with tensors operation

In [24]:
float_16_tensor = Test_tensor.type(torch.float16) #Test_nesor.type(torch.half)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * Test_tensor

tensor([ 9., 36., 81.])

In [26]:
#How to check tensor information #Tensor attribute
#datatype = tensor.dtype
#shape = tensor.shape, tensor.size() --> size() is a function
#device = tensor.device

### 1.6 Manipulating tensor (Tensor Operations)

In [27]:
#Tensor Manipulation (Tensor Operations)
#Addition
#Subtraction
#Multiplication (element-wise)
#Division
#Matrix multiplication (dot product)

In [28]:
#Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
#Multiplication
tensor * 10

tensor([10, 20, 30])

In [30]:
#Subtraction
tensor - 10

tensor([-9, -8, -7])

In [31]:
#Tensor built-in function
torch.mul(tensor, 10), torch.add(tensor, 10), torch.sub(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([-9, -8, -7]))

In [32]:
#Tensor Matrix multiplication
torch.matmul(tensor, tensor)
#Or
#tensor @ tensor

tensor(14)

#####There are two main rules for matrix multiplication needs to be satisfied:
1. The **inner dimension** must match
2. The resulting matrix has the shape of **outer dimension**

###One of the most common errors in deep learning: **Shape Error**
#####To deal with the shape error, we can use ***Transpose**
`Transpose = Tensor.T `


In [33]:
rand_tens = torch.rand(3,2)

rand_tens, rand_tens.T


(tensor([[0.2970, 0.8170],
         [0.6409, 0.1015],
         [0.0533, 0.5011]]),
 tensor([[0.2970, 0.6409, 0.0533],
         [0.8170, 0.1015, 0.5011]]))

### 1.7 Tensor Aggregation
####Finding min, max, mean, sum, etc

In [34]:
rand_tensor = torch.arange(0,100,10)
rand_tensor, rand_tensor.min(), rand_tensor.max(), rand_tensor.type(torch.float32).mean()
#Could be torch.min(rand_tensor), torch.max(rand_tensor), torch.mean(rand_tensor.type(torch.float32))

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 tensor(0),
 tensor(90),
 tensor(45.))

In [35]:
#Why change in dtype for mean() function?
rand_tensor.dtype # torch.int64 == Long datatype
# **NOTE**
#Input dtype must be either a floating point or complex dtype for mean() function
#Thus, we need to change the dtype of the tensor to use mean()
#From the following result, we can also note that arange() function creates tensor with dtype of int64

torch.int64

In [36]:
#Finding index of the min, max, mean value in the tensor
rand_tensor.argmin(), rand_tensor.argmax() # == torch.argmin(rand_tensor), torch.argmax(rand_tensor)


(tensor(0), tensor(9))

In [37]:
tensor = torch.rand(10,10)
tensor.argmax(), tensor.argmin()

(tensor(31), tensor(52))

####Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping: reshapes a tensor to a defined shape
* View: return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking: combine multiple tensors on top of each other (vstack-vertical stack, hstack-horizontal stack)
* Squeeze: removes all `1` dimensions from a tensor
* Unsqueeze: add a `1` dimension to a target tensor
* Permute: Return a view of the input with dimensions permuted (swapped) in a certain way


In [38]:
# example tensor
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [39]:
#Reshape the tensor
#Add an extra dimension
x.reshape(2,5), x.reshape(5,2)

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]))

In [40]:
x.reshape(2,5).shape, x.reshape(5,2).shape

(torch.Size([2, 5]), torch.Size([5, 2]))

In [41]:
# Change the View **Note that a view of a tensor share the same memory as the origianl tensor
z = x.view(2,5)
z[:,0] = 5 #Here we adjusted tensor z
z, x #But checking z and x, both same element has been changed since view()

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [42]:
# Stack tensors on top of each other

stacked = torch.stack([x,x,x,x], dim=0)
stacked


tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])