In [4]:
import numpy as np

In [5]:
# create a 1D array
x = np.array([0, 1, 2, 3, 4, 5, 6])

In [7]:
# find all non-zero elements in x
x[x!=0]

array([1, 2, 3, 4, 5, 6])

In [38]:
# create a 5x5 matrix A with random numbers
A = np.random.randn(5, 5)

# create a 5x5 identity matrix B
B = np.eye(5)

In [39]:
# calculate the following equations
# A + B
# A - B
# A * B (matrix product)
# A' (transpose of A)
A + B

array([[ 0.24106559,  1.58106141,  3.72825688, -0.37155701,  0.88428195],
       [ 1.68043348,  1.88622408,  0.1678164 , -1.45227759, -1.00385795],
       [ 0.72027424, -0.61107632,  0.72827823, -0.38261565, -0.41513977],
       [ 0.83028903, -0.65074747,  0.78734604,  1.67027903,  0.14297529],
       [-0.16985516,  0.29524993,  0.20705078,  0.62814617, -0.97738283]])

In [14]:
A - B

array([[-1.9624023 , -3.16172528, -1.37575593,  0.19331449,  1.23301196],
       [-0.54023301, -3.44689493,  0.41189332,  0.2634931 , -0.32233463],
       [-0.98810722,  0.08898256, -0.81477597,  0.29828431, -2.00060033],
       [-0.86592708, -1.2972045 , -1.676434  , -0.68386101,  0.58099567],
       [ 1.41108757,  1.07136593,  0.56986844,  0.6704895 , -1.11046117]])

In [ ]:
# calculate the mean, sum, max, min value for each column in A


In [15]:
A * B

array([[-0.9624023 , -0.        , -0.        ,  0.        ,  0.        ],
       [-0.        , -2.44689493,  0.        ,  0.        , -0.        ],
       [-0.        ,  0.        ,  0.18522403,  0.        , -0.        ],
       [-0.        , -0.        , -0.        ,  0.31613899,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.11046117]])

In [16]:
A.T

array([[-0.9624023 , -0.54023301, -0.98810722, -0.86592708,  1.41108757],
       [-3.16172528, -2.44689493,  0.08898256, -1.2972045 ,  1.07136593],
       [-1.37575593,  0.41189332,  0.18522403, -1.676434  ,  0.56986844],
       [ 0.19331449,  0.2634931 ,  0.29828431,  0.31613899,  0.6704895 ],
       [ 1.23301196, -0.32233463, -2.00060033,  0.58099567, -0.11046117]])

In [40]:
A

array([[-0.75893441,  1.58106141,  3.72825688, -0.37155701,  0.88428195],
       [ 1.68043348,  0.88622408,  0.1678164 , -1.45227759, -1.00385795],
       [ 0.72027424, -0.61107632, -0.27172177, -0.38261565, -0.41513977],
       [ 0.83028903, -0.65074747,  0.78734604,  0.67027903,  0.14297529],
       [-0.16985516,  0.29524993,  0.20705078,  0.62814617, -1.97738283]])

In [41]:
# normalize A with its max value A_max and min value A_min
# i.e., for any value x in A,
# x = (x - A_min) / (A_max - A_min)
for i in range(5):
    for j in range(5):
        x = A[i,j]
        A[i, j] = (x - A.min()) / (A.max() - A.min())
A

array([[0.21355159, 0.62367139, 1.        , 0.43901216, 0.7823424 ],
       [1.        , 0.9617866 , 0.72049829, 0.1763647 , 0.32697337],
       [0.90604978, 0.45889514, 0.57287261, 0.53562719, 0.52470346],
       [0.94299995, 0.44557097, 0.92857688, 0.88925812, 0.71215502],
       [0.60708608, 0.76329881, 0.73367576, 0.87510715, 0.        ]])

In [42]:
# advanced exercise
# solve the system of equations:
# 3 * x0 + x1 = 9
# x0 + 2 * x1 = 8

# Ax = b 
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [48]:
# compare x with the product of inverse A and b
x - np.linalg.inv(A) * b

array([[-1.6,  4.6],
       [ 3.8, -1.8]])